name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        sudo apt-get -y install libxft2-dev
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DTESTS=ON -DDEV=ON

    - name: Build code style check tool
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build ./dev --config $BUILD_TYPE

    - name: Check code style
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./dev/code_check $GITHUB_WORKSPACE/dev $GITHUB_WORKSPACE/src $GITHUB_WORKSPACE/test

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE --output-on-failure
